# Create: .github/workflows/deploy.yml

name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Create application directory
          sudo mkdir -p /var/www/art-marketplace
          sudo chown ubuntu:ubuntu /var/www/art-marketplace
          cd /var/www/art-marketplace
          
          # Clone or update repository
          if [ -d ".git" ]; then
            echo "Updating existing repository..."
            git pull origin main
          else
            echo "Cloning repository..."
            git clone https://github.com/${{ github.repository }}.git .
          fi
          
          # Install dependencies
          echo "Installing dependencies..."
          npm ci --only=production
          
          # Create environment file
          echo "Creating environment file..."
          cat > .env << 'EOF'
          NODE_ENV=production
          PORT=5000
          FRONTEND_URL=${{ secrets.FRONTEND_URL }}
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          REDIS_URL=redis://localhost:6379
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN=90d
          JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
          CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          EMAIL_HOST=smtp.gmail.com
          EMAIL_PORT=587
          EMAIL_USER=${{ secrets.EMAIL_USER }}
          EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          BCRYPT_ROUNDS=12
          RATE_LIMIT_WINDOW=15
          RATE_LIMIT_MAX=100
          EOF
          
          # Create logs directory
          mkdir -p logs
          
          # Stop existing application
          echo "Stopping existing application..."
          pm2 stop 3rd-hand-art-marketplace-api || echo "App not running"
          
          # Start application
          echo "Starting application..."
          pm2 start ecosystem.config.js --env production
          
          # Save PM2 configuration
          pm2 save
          
          # Setup PM2 startup
          sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu || echo "PM2 startup already configured"
          
          echo "Deployment completed successfully!"
          
          # Show application status
          pm2 status